### ISSUE TITLE
Sporadic error `call on null client` for first RPC call after upgrading from 3.0.0-alpha.30 to 3.0.1-alpha.1, ~1% chance

### ISSUE THREAD

**Issue by mologie** [capnproto/go-capnp#572]
After updating to 3.0.1-alpha.1 from 3.0.0-alpha.30, a load test of mine now fails occasionally with error `schema/avas/corehost/corehost.capnp:CoreFactory.buildInfo: call on null client`.

__I am trying to build a minimal reproducer to narrow this down and post it here.__ (But that might take some time, I'm deferring to update for now.) In the meantime I'd leave the following details here in case someone else stumbles over the issue:

- The environment is a Go HTTP server, which connects to a C++ capnp RPC server within a HTTP request.
- 0.1-2% of requests fail with capnp 3.0.1-alpha.1 regardless for request rate or parallel requests (high variance in failure rate). More requests make it fail more often, linear correlation.
- The affected code is heavily used in production with tens of thousands of daily connections, without issues with capnp 3.0.0-alpha.30.
- No errors are logged to `Logger`.

The affected code is as simple as the following after a successful connection:
```
// (establishment + error checks for tcpConn omitted)
conn := rpc.NewConn(rpc.NewStreamTransport(tcpConn), &rpc.Options{
	Logger: &rpcErrorReporter{sess: s},
})
factory := corehost.CoreFactory(conn.Bootstrap(s.ctx))
buildInfoFuture, buildInfoRelease := factory.BuildInfo(s.ctx, nil)
defer buildInfoRelease()
buildInfo, err := buildInfoFuture.Struct() // err is not nil for 0.2-2% of requests
```

**Comment by mologie** [comment]
Running tests on main nets me the following:
```
--- FAIL: TestPromiseOrdering (0.08s)
    senderpromise_test.go:404:
        	Error Trace:	/Users/okuckertz/Devel/go-capnp/rpc/senderpromise_test.go:404
        	Error:      	Received unexpected error:
        	            	test.capnp:PingPong.echoNum: call on null client
        	Test:       	TestPromiseOrdering
        	Messages:   	call #0 should succeed
FAIL
FAIL	capnproto.org/go/capnp/v3/rpc	0.550s
```

So this is probably related to or a duplicate of #543.

**Comment by lthibault** [comment]
@mologie Firstly, thank you so much for your help on this issue.

Can you try resolving the capability (`factory.Resolve(ctx)` ought to do it) before making any RPC calls?  I suspect this will suffice as a short-term workaround, although we'll obviously want to tackle the underlying issue.

As far as the underlying issue is concerned, Zenhack suggested that his prior work on `WeakRef` may have uncovered the underlying bug, so that might be a good thread to follow.

Please feel free to join our [Matrix community](https://matrix.to/#/#go-capnp:matrix.org) if you need any support.  I'm happy to assist however I can.

**Comment by QuangTung97** [comment]
Any update on this?
@mologie Which version do you think one can revert to in order to avoid this issue?

**Comment by mologie** [comment]
I'm still on `v3.0.0-alpha.30` where this issue does not yet exist. You're missing out on a ton of changes an fixes, but none appear to be as critical as this one. I still plan to debug this eventually when I finally find a week or so to invest here, in hopes to help the project out.

**Comment by QuangTung97** [comment]
@mologie Did you still got this error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb6da5e]

goroutine 2416337 [running]:
capnproto.org/go/capnp/v3/rpc.(*Conn).handleCall.func4.6()
	capnproto.org/go/capnp/v3@v3.0.0-alpha.30/rpc/rpc.go:952 +0x3e
zenhack.net/go/util/deferred.(*Queue).Run(0x1218cf0?)
	zenhack.net/go/util@v0.0.0-20230414204917-531d38494cf5/deferred/queue.go:31 +0x42
capnproto.org/go/capnp/v3/rpc.(*Conn).handleCall(0xc022946b00, {0x12251c0, 0xc020f96c80}, {0x12210e8, 0xc0212b0420})
	capnproto.org/go/capnp/v3@v3.0.0-alpha.30/rpc/rpc.go:844 +0xaba
capnproto.org/go/capnp/v3/rpc.(*Conn).receive.func1()
	capnproto.org/go/capnp/v3@v3.0.0-alpha.30/rpc/rpc.go:604 +0x325
capnproto.org/go/capnp/v3/rpc.(*Conn).receive.(*Conn).backgroundTask.func2()
	capnproto.org/go/capnp/v3@v3.0.0-alpha.30/rpc/rpc.go:286 +0x62
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.10.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 2416334
	golang.org/x/sync@v0.10.0/errgroup/errgroup.go:75 +0x96
# Errors occurred during execution: exit status 2
```

I tried to use `v3.0.0-alpha.30`, but this panic still happened, but with a much lower probability (may be 1 in 10,000,000 reqs)

**Comment by mologie** [comment]
@QuangTung97: No, I am still at alpha.30 and served hundreds of millions of requests over capnp-rpc, and I do not recall seeing that panic in our logs so far.

With a that low probability I might have just gotten lucky so far, but it might also be related to how my code tears down the connection -- we cancel all pending RPC requests before closing the connection. Given that you have a handleCall on a nil ptr, I'd guess there is a bug in this library still, but I avoid it by avoiding this scenario.

This bug fwiw is /still/ on my radar, eventually I will find some time for it and update to the latest version :)
